import styled from 'styled-components'

export const Container = styled.div`
  grid-area: contentarea;
  display: flex;
  align-items: center;
  flex-direction: column;
  animation:scale-up-horizontal-left 1s;
  

  /* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
  ---------------------------------------------- */
  
  @keyframes scale-up-horizontal-left{
    0%  {
      transform:scaleX(.4);
      transform-origin:left center
    }
    100%  {
      transform:scaleX(1);
      transform-origin:left center
    }
  };

  h1 {
    align-self: center;
    margin: 30px;
    font-size: 2rem;
  }
`;

export const SkillSection = styled.div`
  /* background-color: ${({ theme }) => theme.main.primary }; */
  background: rgb(49,49,67);
  background: linear-gradient(90deg, rgba(49,49,67,1) 0%, rgba(32,36,50,1) 65%, rgba(24,34,41,1) 100%);
  display: flex;
  align-items: center;
  justify-content: start;
  flex-wrap: wrap;
  width: 100%;
  
  h2 {
    color: white;
    font-size: 1.3rem;
    margin: 0 23px;
  }

  a {
    display: flex;
    align-items: center;
    margin: 13px;
  }
`;